// This file maps neckline names to example image URLs for the AI Neckline Generator UI
export const necklineImages: Record<string, string> = {
  "Boat Neck": "/necklines/boat-neck.png",
  "Jewel": "/necklines/jewel.png",
  "Square": "/necklines/square.png",
  "Scoop": "/necklines/scoop.png",
  "V-Neck": "/necklines/v-neck.png",
  "Asymmetric": "/necklines/asymmetric.png",
  "High Neck": "/necklines/high-neck.png",
  "Halter": "/necklines/halter.png",
  "Off-Shoulders": "/necklines/off-shoulders.png",
  "Queen Anna": "/necklines/queen-anna.png",
  "Halter Strap": "/necklines/halter-strap.png",
  "Illusion": "/necklines/illusion.png",
  "Sweetheart": "/necklines/sweetheart.png",
  "Strapless": "/necklines/strapless.png",
  "Deep V-Neck": "/necklines/deep-v-neck.png",
  "Deep Round": "/necklines/deep-round.png",
  "Collar": "/necklines/collar.png",
  "Off-the-Shoulder": "/necklines/off-the-shoulder.png",
  "Scoop Neck": "/necklines/scoop-neck.png",
  "Turtleneck": "/necklines/turtleneck.png",
  "Cowl": "/necklines/cowl.png",
  "Keyhole": "/necklines/keyhole.png",
  "Queen Anne": "/necklines/queen-anne.png",
  "Bateau": "/necklines/bateau.png",
  "One Shoulder": "/necklines/one-shoulder.png",
  "Portrait": "/necklines/portrait.png",
  "Surplice": "/necklines/surplice.png",
  "Yoke": "/necklines/yoke.png"
};
